/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "Functions",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Functions__factory>;
    getContractFactory(
      name: "MLP_1L_1n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_1L_1n__factory>;
    getContractFactory(
      name: "MLP_2L_1n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_2L_1n__factory>;
    getContractFactory(
      name: "MLP_2L_2n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_2L_2n__factory>;
    getContractFactory(
      name: "MLP_2L_3n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_2L_3n__factory>;
    getContractFactory(
      name: "MLP_2L_4n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_2L_4n__factory>;
    getContractFactory(
      name: "MLP_3L_1n1n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_3L_1n1n__factory>;
    getContractFactory(
      name: "MLP_3L_2n1n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_3L_2n1n__factory>;
    getContractFactory(
      name: "MLP_3L_3n1n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_3L_3n1n__factory>;
    getContractFactory(
      name: "MLP_3L_4n1n",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MLP_3L_4n1n__factory>;

    getContractAt(
      name: "Functions",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Functions>;
    getContractAt(
      name: "MLP_1L_1n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_1L_1n>;
    getContractAt(
      name: "MLP_2L_1n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_2L_1n>;
    getContractAt(
      name: "MLP_2L_2n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_2L_2n>;
    getContractAt(
      name: "MLP_2L_3n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_2L_3n>;
    getContractAt(
      name: "MLP_2L_4n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_2L_4n>;
    getContractAt(
      name: "MLP_3L_1n1n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_3L_1n1n>;
    getContractAt(
      name: "MLP_3L_2n1n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_3L_2n1n>;
    getContractAt(
      name: "MLP_3L_3n1n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_3L_3n1n>;
    getContractAt(
      name: "MLP_3L_4n1n",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MLP_3L_4n1n>;

    deployContract(
      name: "Functions",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Functions>;
    deployContract(
      name: "MLP_1L_1n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_1L_1n>;
    deployContract(
      name: "MLP_2L_1n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_1n>;
    deployContract(
      name: "MLP_2L_2n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_2n>;
    deployContract(
      name: "MLP_2L_3n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_3n>;
    deployContract(
      name: "MLP_2L_4n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_4n>;
    deployContract(
      name: "MLP_3L_1n1n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_1n1n>;
    deployContract(
      name: "MLP_3L_2n1n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_2n1n>;
    deployContract(
      name: "MLP_3L_3n1n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_3n1n>;
    deployContract(
      name: "MLP_3L_4n1n",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_4n1n>;

    deployContract(
      name: "Functions",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Functions>;
    deployContract(
      name: "MLP_1L_1n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_1L_1n>;
    deployContract(
      name: "MLP_2L_1n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_1n>;
    deployContract(
      name: "MLP_2L_2n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_2n>;
    deployContract(
      name: "MLP_2L_3n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_3n>;
    deployContract(
      name: "MLP_2L_4n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_2L_4n>;
    deployContract(
      name: "MLP_3L_1n1n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_1n1n>;
    deployContract(
      name: "MLP_3L_2n1n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_2n1n>;
    deployContract(
      name: "MLP_3L_3n1n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_3n1n>;
    deployContract(
      name: "MLP_3L_4n1n",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MLP_3L_4n1n>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
